package com.example;

import com.example.Fichas.Juego;

/**
 *
 * @author a20alejandrofs & a22diegopc
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    Juego juego;

    public VentanaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        botonPausa = new javax.swing.JToggleButton();
        contador = new javax.swing.JLabel();
        empezar = new javax.swing.JButton();
        panelJuego = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diego y Alejandro presentan el TETRIS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(102, 102, 255));
        contenedor.setMinimumSize(new java.awt.Dimension(460, 900));
        contenedor.setPreferredSize(new java.awt.Dimension(460, 900));
        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPausa.setBackground(new java.awt.Color(255, 51, 51));
        botonPausa.setForeground(new java.awt.Color(255, 255, 255));
        botonPausa.setText("Pausa");
        botonPausa.setMinimumSize(new java.awt.Dimension(80, 40));
        botonPausa.setPreferredSize(new java.awt.Dimension(80, 40));
        botonPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausaActionPerformed(evt);
            }
        });
        contenedor.add(botonPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        contador.setText("Puntos");
        contenedor.add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        empezar.setFocusable(true);
        empezar.setBackground(new java.awt.Color(0, 0, 153));
        empezar.setForeground(new java.awt.Color(255, 255, 255));
        empezar.setText("Empezar");
        empezar.setPreferredSize(new java.awt.Dimension(80, 40));
        empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarActionPerformed(evt);
            }
        });
        contenedor.add(empezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        panelJuego.setBackground(new java.awt.Color(0, 0, 0));
        panelJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 5));
        panelJuego.setMinimumSize(new java.awt.Dimension(300, 700));
        panelJuego.setPreferredSize(new java.awt.Dimension(400, 800));
        panelJuego.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelJuegoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );

        contenedor.add(panelJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        getContentPane().add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarActionPerformed
        juego = new Juego(panelJuego, this);
        panelJuego.requestFocus();
    }//GEN-LAST:event_empezarActionPerformed

    public void mostrarPerder(){

        panelJuego.setVisible(false);
        contenedor.remove(this.panelJuego);
    }
    
    private void panelJuegoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelJuegoKeyPressed
        switch (evt.getKeyChar()) {
            case 'a': {
                juego.moverFichaIzquierda();
                break;
            }
            case 's': {
                juego.moverFichaAbajo();
                break;
            }
            case 'd': {
                juego.moverFichaDerecha();
                break;
            }
            case 'w': {
                juego.rotarFicha();
                break;
            }
            default: {

                break;
            }
        }
    }//GEN-LAST:event_panelJuegoKeyPressed

    private void botonPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausaActionPerformed
        juego.pausa();
    }//GEN-LAST:event_botonPausaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonPausa;
    private javax.swing.JLabel contador;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton empezar;
    private javax.swing.JPanel panelJuego;
    // End of variables declaration//GEN-END:variables
}
