package com.mycompany.hacienda;

/**
 *
 * @author a20alejandrofs
 */
public class Hacienda extends javax.swing.JFrame {
    double iva = 0.21, descuento = 0.0;

    /**
     * Creates new form Hacienda
     */
    public Hacienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configuracion = new javax.swing.JDialog();
        labelIva = new javax.swing.JLabel();
        labelDescuento = new javax.swing.JLabel();
        escribirIva = new javax.swing.JTextField();
        escribirDescuento = new javax.swing.JTextField();
        botonDialogGuardar = new javax.swing.JButton();
        botonDialogCerrar = new javax.swing.JButton();
        botonConfiguracion = new javax.swing.JButton();
        botonCalcular = new javax.swing.JButton();
        labelUnidades = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        escribirPrecio = new javax.swing.JTextField();
        resultado = new javax.swing.JLabel();
        escribirUnidades = new javax.swing.JTextField();

        configuracion.setTitle("Configuracion");
        configuracion.setResizable(false);
        configuracion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIva.setText("% IVA");
        configuracion.getContentPane().add(labelIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        labelDescuento.setText("% DESCUENTO");
        configuracion.getContentPane().add(labelDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));
        configuracion.getContentPane().add(escribirIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 80, -1));
        configuracion.getContentPane().add(escribirDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 80, -1));

        botonDialogGuardar.setText("Guardar");
        botonDialogGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDialogGuardarActionPerformed(evt);
            }
        });
        configuracion.getContentPane().add(botonDialogGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        botonDialogCerrar.setText("Cerrar");
        botonDialogCerrar.setToolTipText("");
        botonDialogCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDialogCerrarActionPerformed(evt);
            }
        });
        configuracion.getContentPane().add(botonDialogCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculador");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonConfiguracion.setText("Configuracion");
        botonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(botonConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        botonCalcular.setText("Calcular");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(botonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        labelUnidades.setText("Unidades");
        getContentPane().add(labelUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        labelPrecio.setText("Precio");
        getContentPane().add(labelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        labelTotal.setText("Total:");
        getContentPane().add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        getContentPane().add(escribirPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 80, -1));

        resultado.setText("Click en calcular");
        resultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));
        getContentPane().add(escribirUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDialogGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDialogGuardarActionPerformed
        if (!escribirIva.getText().isEmpty()){
            iva = Double.parseDouble(escribirIva.getText())/100;
        } else{
            iva = 0.21;
        }
        if (!escribirDescuento.getText().isEmpty()){
            descuento = Double.parseDouble(escribirDescuento.getText())/100;
        } else{
            descuento = 0.0;
        }
        botonDialogCerrarActionPerformed(evt);
    }//GEN-LAST:event_botonDialogGuardarActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        if (!escribirUnidades.getText().isEmpty() && !escribirPrecio.getText().isEmpty()){
            double numUnidades = Double.parseDouble(escribirUnidades.getText()), numPrecio = Double.parseDouble(escribirPrecio.getText());
            double total = numUnidades*((numPrecio+numPrecio*iva)-((numPrecio+numPrecio*iva)*descuento));
            resultado.setText(String.valueOf(total));
        } else{
            resultado.setText("Escribe valores:)");
        }
        
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void botonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfiguracionActionPerformed
        configuracion.setVisible(true);
        configuracion.setSize(this.getSize());
    }//GEN-LAST:event_botonConfiguracionActionPerformed

    private void botonDialogCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDialogCerrarActionPerformed
        configuracion.setVisible(false);
    }//GEN-LAST:event_botonDialogCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hacienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hacienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hacienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hacienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hacienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonConfiguracion;
    private javax.swing.JButton botonDialogCerrar;
    private javax.swing.JButton botonDialogGuardar;
    private javax.swing.JDialog configuracion;
    private javax.swing.JTextField escribirDescuento;
    private javax.swing.JTextField escribirIva;
    private javax.swing.JTextField escribirPrecio;
    private javax.swing.JTextField escribirUnidades;
    private javax.swing.JLabel labelDescuento;
    private javax.swing.JLabel labelIva;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelUnidades;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
