drop table if exists users;
create table users (
    id bigint generated by default as identity,
    name varchar(255) not null, 
    email varchar(255) not null,
    primary key (id)
);

insert into 
    users (name, email) 
    values 
        ('John Doe', 'john.doe@example.com');


