package com.mycompany.grados;

/**
 *
 * @author a20alejandrofs
 */
public class Grados extends javax.swing.JFrame {

    /**
     * Creates new form Grados
     */
    public Grados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Convertir = new javax.swing.JButton();
        Celsius = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();
        Farenhigh = new javax.swing.JLabel();
        texto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Convertir.setText("Convertir");
        Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirActionPerformed(evt);
            }
        });
        getContentPane().add(Convertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        Celsius.setText("Celsius");
        getContentPane().add(Celsius, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        Resultado.setText("Click en convertir");
        getContentPane().add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        Farenhigh.setText("Farenhigh");
        getContentPane().add(Farenhigh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirActionPerformed
        if (!texto.getText().isEmpty()){
            Resultado.setText(String.valueOf(Integer.parseInt(texto.getText())*1.8+32));
        } else{
            Resultado.setText("Error");
        }
    }//GEN-LAST:event_ConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Celsius;
    private javax.swing.JButton Convertir;
    private javax.swing.JLabel Farenhigh;
    private javax.swing.JLabel Resultado;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
